/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_call_setting {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_call_setting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_call_setting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsua_call_setting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlag(long value) {
    pjsuaJNI.pjsua_call_setting_flag_set(swigCPtr, this, value);
  }

  public long getFlag() {
    return pjsuaJNI.pjsua_call_setting_flag_get(swigCPtr, this);
  }

  public void setReq_keyframe_method(long value) {
    pjsuaJNI.pjsua_call_setting_req_keyframe_method_set(swigCPtr, this, value);
  }

  public long getReq_keyframe_method() {
    return pjsuaJNI.pjsua_call_setting_req_keyframe_method_get(swigCPtr, this);
  }

  public void setAud_cnt(long value) {
    pjsuaJNI.pjsua_call_setting_aud_cnt_set(swigCPtr, this, value);
  }

  public long getAud_cnt() {
    return pjsuaJNI.pjsua_call_setting_aud_cnt_get(swigCPtr, this);
  }

  public void setVid_cnt(long value) {
    pjsuaJNI.pjsua_call_setting_vid_cnt_set(swigCPtr, this, value);
  }

  public long getVid_cnt() {
    return pjsuaJNI.pjsua_call_setting_vid_cnt_get(swigCPtr, this);
  }

  public void setVtc_type(long value) {
    pjsuaJNI.pjsua_call_setting_vtc_type_set(swigCPtr, this, value);
  }

  public long getVtc_type() {
    return pjsuaJNI.pjsua_call_setting_vtc_type_get(swigCPtr, this);
  }

  public void setVtc_id(int value) {
	  pjsuaJNI.pjsua_call_setting_vtc_id_set(swigCPtr, this, value);
  }
  
  public long getVtc_id() {
	return pjsuaJNI.pjsua_call_setting_vtc_id_get(swigCPtr, this);
  }

  public void seUtype(long value) {
    pjsuaJNI.pjsua_call_setting_utype_set(swigCPtr, this, value);
  }

  public long getUtype() {
    return pjsuaJNI.pjsua_call_setting_utype_get(swigCPtr, this);
  }

  public void setUid(int value) {
	  pjsuaJNI.pjsua_call_setting_uid_set(swigCPtr, this, value);
  }
  
  public long getUid() {
	return pjsuaJNI.pjsua_call_setting_uid_get(swigCPtr, this);
  }

  public pjsua_call_setting() {
    this(pjsuaJNI.new_pjsua_call_setting(), true);
  }

}
